name: Tests and coverage

on: [push, pull_request]

jobs:
  phpinsights:
      runs-on: ubuntu-latest
      name: Testing and coverage check
      steps:
        - uses: actions/checkout@v2
        - uses: shivammathur/setup-php@v1
          with:
              php-version: 8.0
        - run: cp .env.example .env.testing
        - run: cp .env.example .env
        - run: composer install --prefer-dist --no-progress --no-suggest
        - run: ./vendor/bin/sail up -d
        - run: sleep 60s
        - run: docker-compose exec -T -u sail laravel.test php artisan migrate
        - run: docker-compose exec -T -u sail laravel.test php artisan test --coverage-xml reports
        - uses: codecov/codecov-action@v1